version: 2.1

executors:
  python:
    working_directory: ~/sway
    docker:
      - image: circleci/python:3.7

  test-status-reporter:
    docker:
      - image: bash:latest

commands:
  run-tests:
    description: "Run Sway tests"
    parameters:
      python-version:
        type: string
    steps:
      - checkout
      - run: sudo pip install tox poetry
      - run: tox -e lint
      - run: tox -e << parameters.python-version >>
        # - run: tox -e functional

jobs:

  test-2-7:
    executor: python
    docker:
      - image: circleci/python:2.7
    steps:
      - run-tests:
          python-version: py27

  test-3-5:
    executor: python
    docker:
      - image: circleci/python:3.5
    steps:
      - run-tests:
          python-version: py35

  test-3-6:
    executor: python
    docker:
      - image: circleci/python:3.6
    steps:
      - run-tests:
          python-version: py36

  test-3-7:
    executor: python
    docker:
      - image: circleci/python:3.7
    steps:
      - run-tests:
          python-version: py37

  tests-passed:
    executor: test-status-reporter
    steps:
      - run:
          name: All tests passed
          command: |
            echo "All test checks (linting + unit tests + functional tests) passed"

  deploy-to-pypi:
    executor: python
    steps:
      - checkout
      - run: echo "Not yet implemented"

test-filters: &test-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/

tag-filters: &tag-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

workflows:
  version: 2.1
  sway-workflow:
    jobs:
      - test-2-7:
          filters: *test-filters
      - test-3-5:
          filters: *test-filters
      - test-3-6:
          filters: *test-filters
      - test-3-7:
          filters: *test-filters
      - tests-passed:
          requires:
            - test-2-7
            - test-3-5
            - test-3-6
            - test-3-7
          filters: *test-filters
      - deploy-to-pypi:
          requires:
            - tests-passed
          filters: *tag-filters
